#!/usr/bin/env node
// Reads .env and generates env.js for browser consumption
const fs = require('fs');
const path = require('path');

const envPath = path.join(__dirname, '.env');
const outputPath = path.join(__dirname, 'env.js');

if (!fs.existsSync(envPath)) {
  console.warn('⚠️  .env file not found. Creating env.js with placeholders.');
  const placeholder = `window.__ENV__ = {
  SUPABASE_URL: 'https://YOUR-PROJECT-REF.supabase.co',
  SUPABASE_ANON_KEY: 'YOUR_PUBLIC_ANON_KEY'
};
`;
  fs.writeFileSync(outputPath, placeholder, 'utf8');
  process.exit(0);
}

// Parse .env
const envContent = fs.readFileSync(envPath, 'utf8');
const envVars = {};

envContent.split('\n').forEach(line => {
  line = line.trim();
  if (!line || line.startsWith('#')) return;
  const [key, ...valueParts] = line.split('=');
  if (key && valueParts.length > 0) {
    let value = valueParts.join('=').trim();
    // Remove surrounding quotes if present (both single and double)
    if ((value.startsWith('"') && value.endsWith('"')) || 
        (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    envVars[key.trim()] = value;
  }
});

// Generate env.js
const jsContent = `// Auto-generated from .env by generate-env.js
// Do not edit this file directly - edit .env instead

window.__ENV__ = ${JSON.stringify(envVars, null, 2)};
`;

fs.writeFileSync(outputPath, jsContent, 'utf8');
console.log('✅ Generated env.js from .env');
